name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Hi, this is part of the greeting"
      - name: Print goodbye
        run: echo "Done - bye!"
